[tool.poetry]
name = "mscmcldap"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.19"
wheel = "0.29.0"
django = "1.10.5"
django-environ = "0.4.1"
dj-database-url = "0.4.2"
django-compressor = "2.1.1"
django-model-utils = "2.6.1"
psycopg2 = "2.8.6"
pytz = "2016.10"
ldap3 = "^2.9.1"
djangorestframework = "3.6.3"
unipath = "1.1"
coverage = "4.3.4"
django-coverage-plugin = "1.4.2"
sphinx = "1.5.2"
django-extensions = "1.7.6"
werkzeug = "0.11.15"
django-test-plus = "1.0.17"
factory-boy = "2.8.1"
django-debug-toolbar = "1.6"
pytest-django = "3.1.2"
pytest-sugar = "0.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
