# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    print('Iniciando comandos SQL para mockar views')

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS v_setor;
            """
        ),
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS v_pessoa;
            """
        ),
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS v_cmcfuncionarios;
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_setor (
                set_id serial primary key,
                set_nome character varying(500) not null,
                set_sigla character varying(100) not null,
                set_id_superior integer,
                set_ativo boolean not null, 
                set_tipo character varying(1)
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_pessoa(
                pes_matricula serial primary key,
                pes_nome character varying(500) not null,
                set_id integer not null
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_centro_custo(
                centrocusto serial primary key,
                local character varying(500),
                descricao character varying(500) not null,
                ativoinativoai character varying(1) not null,
                codigoresponsavel integer
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_item(
                item serial primary key,
                unidade character varying(10) not null,
                classificacao character varying(10) not null,
                desc_classificacao character varying(500) not null,
                desc_item character varying(500) not null,
                estocavel character varying(1) not null,
                ativoinativoai character varying(1) not null,
                valor character varying(100),
                ativo_classificacao character varying(1) not null,
                itememanalisesn character varying(1) not null
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_cmcfuncionarios(
                pessoa serial primary key,
                matricula integer not null,
                pes_nome character varying(500) not null,
                funcao integer,
                set_id integer not null,
                ind_estagiario integer not null
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_spl_reuniao_comissao(
                rec_id serial primary key,
                con_id integer not null,
                rec_tipo_reuniao character varying(500) not null,
                rec_numero character varying(100),
                versao integer,
                rec_data date
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_spl_conjunto_vereadores(
                con_id serial primary key,
                con_sigla character varying(500),
                con_maximo integer,
                ut_id integer,
                ini_nome text,
                ini_ativa boolean,
                tin_id integer,
                versao integer,
                ini_codigo_prefeitura integer,
                con_descricao text,
                con_site_ordem integer,
                con_email character varying(500)
            );
            """
        ),
        migrations.RunSQL(
            """
            CREATE TABLE v_spl_pauta_comissao(
                pac_id serial primary key,
                rec_id integer not null,
                pac_liberada boolean,
                pac_notificada boolean,
                versao integer
            );
            """
        )
    ]

    print('Finalizando comandos SQL para mockar views')
