# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2021-03-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='v_centro_custo',
            fields=[
                ('centrocusto', models.IntegerField(primary_key=True, serialize=False)),
                ('local', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(max_length=500)),
                ('ativoinativoai', models.CharField(max_length=1)),
                ('codigoresponsavel', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'v_centro_custo',
                'verbose_name_plural': 'Centros de Custo',
            },
        ),
        migrations.CreateModel(
            name='v_cmcfuncionarios',
            fields=[
                ('pessoa', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField()),
                ('pes_nome', models.CharField(max_length=500)),
                ('funcao', models.IntegerField(blank=True, null=True)),
                ('set_id', models.IntegerField()),
                ('ind_estagiario', models.IntegerField()),
                ('cpf', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'v_cmcfuncionarios',
            },
        ),
        migrations.CreateModel(
            name='v_item',
            fields=[
                ('item', models.IntegerField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(max_length=10)),
                ('classificacao', models.CharField(max_length=10)),
                ('desc_classificacao', models.CharField(max_length=500)),
                ('desc_item', models.CharField(max_length=500)),
                ('estocavel', models.CharField(max_length=1)),
                ('ativoinativoai', models.CharField(max_length=1)),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo_classificacao', models.CharField(max_length=1)),
                ('itememanalisesn', models.CharField(max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'v_item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='v_pessoa',
            fields=[
                ('pes_matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('pes_nome', models.CharField(max_length=500)),
                ('set_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'v_pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='v_setor',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('set_nome', models.CharField(max_length=500)),
                ('set_sigla', models.CharField(max_length=100)),
                ('set_id_superior', models.IntegerField(blank=True, null=True)),
                ('set_ativo', models.BooleanField()),
                ('set_tipo', models.CharField(max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'v_setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='v_spl_cargos_mesa',
            fields=[
                ('matricula', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ini_nome', models.CharField(max_length=100)),
                ('crg_nome', models.CharField(max_length=50)),
                ('crg_ordem', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'v_spl_cargos_mesa',
            },
        ),
        migrations.CreateModel(
            name='v_spl_conjunto_vereadores',
            fields=[
                ('con_id', models.IntegerField(primary_key=True, serialize=False)),
                ('con_sigla', models.CharField(max_length=200)),
                ('con_maximo', models.IntegerField(blank=True, null=True)),
                ('ut_id', models.IntegerField()),
                ('ini_ativa', models.BooleanField()),
                ('tin_id', models.IntegerField()),
                ('versao', models.IntegerField()),
                ('ini_codigo_prefeitura', models.IntegerField()),
                ('con_descricao', models.CharField(max_length=500)),
                ('ini_nome', models.CharField(max_length=500)),
                ('con_site_ordem', models.IntegerField()),
                ('con_email', models.CharField(max_length=500)),
            ],
            options={
                'managed': False,
                'db_table': 'v_spl_conjunto_vereadores',
            },
        ),
        migrations.CreateModel(
            name='v_spl_pauta_comissao',
            fields=[
                ('pac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rec_id', models.IntegerField()),
                ('pac_liberada', models.BooleanField()),
                ('pac_notificada', models.BooleanField()),
                ('versao', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'v_spl_pauta_comissao',
            },
        ),
        migrations.CreateModel(
            name='v_spl_reuniao_comissao',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('con_id', models.IntegerField()),
                ('rec_tipo_reuniao', models.CharField(max_length=500)),
                ('rec_numero', models.CharField(max_length=100)),
                ('versao', models.IntegerField()),
                ('rec_data', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'v_spl_reuniao_comissao',
            },
        ),
        migrations.CreateModel(
            name='v_spl_vereador',
            fields=[
                ('ver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=4)),
                ('ver_sexo', models.CharField(max_length=1)),
                ('ut_id', models.IntegerField()),
                ('ini_nome', models.CharField(max_length=100)),
                ('ini_ativa', models.BooleanField()),
                ('ver_nome_completo', models.CharField(max_length=100)),
                ('ini_codigo_prefeitura', models.IntegerField()),
                ('ver_site', models.CharField(max_length=250)),
                ('ver_biografia', models.TextField()),
                ('ver_redes_sociais', models.CharField(max_length=250)),
                ('ver_fone_principal', models.CharField(max_length=20)),
                ('ver_fones', models.CharField(max_length=100)),
                ('ver_legislaturas', models.CharField(max_length=100)),
                ('ver_localizacao', models.CharField(max_length=50)),
                ('ver_partido', models.CharField(max_length=100)),
                ('arq_id', models.IntegerField()),
                ('arq_id_biografia', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'v_spl_vereador',
            },
        ),
    ]
