[program:mscmc]
command=/usr/share/webapps/mscmcldap/deploy/staging/run.sh
directory=/usr/share/webapps/mscmc
user=www-data  
stopsignal=KILL  
redirect_stderr=True  
stdout_logfile=/var/log/supervisor/mscmc.stdout.log  
stderr_logfile=/var/log/supervisor/mscmc.stderr.log  